`timescale 1ns/1ns
`default_nettype none

/* Generated by Yosys 0.47+116 (git sha1 4b3c03dab, ccache clang++ 18.1.8 -Og -fPIC -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address) */

(* tamara_triplicate =  1  *)
(* top =  1  *)
(* src = "../tests/verilog/not_dff_tmr.sv:5.1-25.10" *)
module not_dff_tmr(a, clk, o, err);
  (* src = "../tests/verilog/not_dff_tmr.sv:13.7-13.9" *)
  (* tamara_cone = "1" *)
  reg \$auto$logic_graph.cpp:303:replicate$\ff__replica1_cone1__$6 ;
  (* src = "../tests/verilog/not_dff_tmr.sv:13.7-13.9" *)
  (* tamara_cone = "1" *)
  reg \$auto$logic_graph.cpp:304:replicate$\ff__replica2_cone1__$7 ;
  wire \$auto$voter_builder.cpp:38:build$A$10 ;
  wire \$auto$voter_builder.cpp:39:build$B$11 ;
  wire \$auto$voter_builder.cpp:40:build$C$12 ;
  wire \$auto$voter_builder.cpp:43:build$OUT$13 ;
  wire \$auto$voter_builder.cpp:44:build$ERR$14 ;
  wire \$auto$voter_builder.cpp:50:build$not0_and2_wire$15 ;
  wire \$auto$voter_builder.cpp:54:build$not1_and3_wire$17 ;
  wire \$auto$voter_builder.cpp:58:build$not2_and5_wire$19 ;
  wire \$auto$voter_builder.cpp:63:build$and0_or0_wire$21 ;
  wire \$auto$voter_builder.cpp:67:build$and1_or0_wire$23 ;
  wire \$auto$voter_builder.cpp:71:build$and2_or1_wire$25 ;
  wire \$auto$voter_builder.cpp:75:build$and3_or1_wire$27 ;
  wire \$auto$voter_builder.cpp:79:build$and4_or2_wire$29 ;
  wire \$auto$voter_builder.cpp:83:build$and5_or3_wire$31 ;
  wire \$auto$voter_builder.cpp:88:build$or0_or2_wire$33 ;
  wire \$auto$voter_builder.cpp:92:build$or1_or3_wire$35 ;
  (* src = "../tests/verilog/not_dff_tmr.sv:6.17-6.18" *)
  input a;
  wire a;
  (* src = "../tests/verilog/not_dff_tmr.sv:7.17-7.20" *)
  input clk;
  wire clk;
  (* src = "../tests/verilog/not_dff_tmr.sv:10.18-10.21" *)
  (* tamara_error_sink = 32'd1 *)
  output err;
  wire err;
  (* src = "../tests/verilog/not_dff_tmr.sv:13.7-13.9" *)
  (* tamara_cone = "1" *)
  (* tamara_original = 32'd1 *)
  reg ff;
  (* src = "../tests/verilog/not_dff_tmr.sv:8.18-8.19" *)
  output o;
  wire o;
  assign \$auto$voter_builder.cpp:38:build$A$10  = ! (* src = "../tests/verilog/not_dff_tmr.sv:19.12-19.15" *) (* tamara_cone = "1" *) \$auto$logic_graph.cpp:303:replicate$\ff__replica1_cone1__$6 ;
  (* \always_ff  = 32'd1 *)
  (* src = "../tests/verilog/not_dff_tmr.sv:15.1-17.4" *)
  (* tamara_cone = "1" *)
  always @(posedge clk)
    \$auto$logic_graph.cpp:303:replicate$\ff__replica1_cone1__$6  <= a;
  assign \$auto$voter_builder.cpp:39:build$B$11  = ! (* src = "../tests/verilog/not_dff_tmr.sv:19.12-19.15" *) (* tamara_cone = "1" *) \$auto$logic_graph.cpp:304:replicate$\ff__replica2_cone1__$7 ;
  (* \always_ff  = 32'd1 *)
  (* src = "../tests/verilog/not_dff_tmr.sv:15.1-17.4" *)
  (* tamara_cone = "1" *)
  always @(posedge clk)
    \$auto$logic_graph.cpp:304:replicate$\ff__replica2_cone1__$7  <= a;
  assign \$auto$voter_builder.cpp:50:build$not0_and2_wire$15  = ! (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:38:build$A$10 ;
  assign \$auto$voter_builder.cpp:54:build$not1_and3_wire$17  = ! (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:39:build$B$11 ;
  assign \$auto$voter_builder.cpp:58:build$not2_and5_wire$19  = ! (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:40:build$C$12 ;
  assign \$auto$voter_builder.cpp:63:build$and0_or0_wire$21  = \$auto$voter_builder.cpp:39:build$B$11  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:40:build$C$12 ;
  assign \$auto$voter_builder.cpp:67:build$and1_or0_wire$23  = \$auto$voter_builder.cpp:38:build$A$10  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:40:build$C$12 ;
  assign \$auto$voter_builder.cpp:71:build$and2_or1_wire$25  = \$auto$voter_builder.cpp:50:build$not0_and2_wire$15  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:40:build$C$12 ;
  assign \$auto$voter_builder.cpp:75:build$and3_or1_wire$27  = \$auto$voter_builder.cpp:54:build$not1_and3_wire$17  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:38:build$A$10 ;
  assign \$auto$voter_builder.cpp:79:build$and4_or2_wire$29  = \$auto$voter_builder.cpp:38:build$A$10  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:39:build$B$11 ;
  assign \$auto$voter_builder.cpp:83:build$and5_or3_wire$31  = \$auto$voter_builder.cpp:58:build$not2_and5_wire$19  && (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:39:build$B$11 ;
  assign \$auto$voter_builder.cpp:88:build$or0_or2_wire$33  = \$auto$voter_builder.cpp:63:build$and0_or0_wire$21  || (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:67:build$and1_or0_wire$23 ;
  assign \$auto$voter_builder.cpp:92:build$or1_or3_wire$35  = \$auto$voter_builder.cpp:71:build$and2_or1_wire$25  || (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:75:build$and3_or1_wire$27 ;
  assign \$auto$voter_builder.cpp:43:build$OUT$13  = \$auto$voter_builder.cpp:88:build$or0_or2_wire$33  || (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:79:build$and4_or2_wire$29 ;
  assign \$auto$voter_builder.cpp:44:build$ERR$14  = \$auto$voter_builder.cpp:92:build$or1_or3_wire$35  || (* tamara_voter = 32'd1 *) \$auto$voter_builder.cpp:83:build$and5_or3_wire$31 ;
  assign \$auto$voter_builder.cpp:40:build$C$12  = ! (* src = "../tests/verilog/not_dff_tmr.sv:19.12-19.15" *) (* tamara_cone = "1" *) (* tamara_original = 32'd1 *) ff;
  (* \always_ff  = 32'd1 *)
  (* src = "../tests/verilog/not_dff_tmr.sv:15.1-17.4" *)
  (* tamara_cone = "1" *)
  (* tamara_original = 32'd1 *)
  always @(posedge clk)
    ff <= a;
  assign o = \$auto$voter_builder.cpp:43:build$OUT$13 ;
  assign err = \$auto$voter_builder.cpp:44:build$ERR$14 ;
endmodule

module testbench;
    logic a;
    logic clk;
    logic o;
    logic err;

    not_dff_tmr top(
        .a(a),
        .clk(clk),
        .o(o),
        .err(err)
    );

    initial begin
        $display("Starting testbench");
        $dumpfile("not_dff_tmr.vcd");
        $dumpvars;

        // reset everything
        a = 0;
        clk = 0;

        // clock on
        clk = 1;
        #10;

        // clock off
        clk = 0;
        #10;

        $display("done");
    end
endmodule
