gantt_mermaid:
    mmdc -i gantt.mmdc -o diagrams/gantt_mermaid.pdf -b transparent -t default -f
    cd diagrams && dvisvgm --pdf --optimize --no-fonts --exact-bbox --bbox=min --color gantt_mermaid.pdf


